version: "2"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  app:
    image: org.seedstack.samples/ddd-sample
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://db:27017/${DB_NAME}
